# ----
# Site

title: 과학당 | 매일 과학, 바른 습관
url: 
baseurl: 
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Jekyll template with example content for a not-for-profit organisation.
author:
  name: UtoPlanet
  email: utoplanet8@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Instagram
  links:
    - https://www.instagram.com/uto_planet/

# -----
# Build

timezone: ko/KR

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
